In [ ]:
QUESTION 1.

In [3]:
import numpy as np

#zero vectors
zero_vector = np.zeros(3)
print(zero_vector)

[0. 0. 0.]


In [4]:
#one vector 
one_vector = np.ones(3)
print(one_vector)

[1. 1. 1.]


In [5]:
#square matrix
square_matrix = np.array([[1,2],[3,4]])
print(square_matrix)


[[1 2]
 [3 4]]


In [6]:
#diagnal matrix
diagnal_matrix = np.diag([1,2,3])
print(diagnal_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [9]:
#identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#symmetric matrix
symm_matrix = np.array([[1,2],[3,4]])
print(symm_matrix)

[[1 2]
 [3 4]]


In [ ]:
QUESTION 2.

In [11]:
#STOCK PURCHASE WITH VECTORS
p = np.array([1_000_000, 800_000, 500_000])

#quanity vecctor

n = np.array([3,4,5])

#total
total_cost = np.dot(p,n)
print(total_cost)

8700000


In [ ]:
QUESTION 3

In [15]:
#MNIST
from sklearn.datasets import load_digits
x = load_digits().data

similarity = np.dot(x[0],x[9])
print(similarity)

similarity_matrix = x @ x.T
print(similarity_matrix)

2807.0
[[3070. 1866. 2264. ... 2812. 3006. 2898.]
 [1866. 4209. 3432. ... 3906. 3083. 3307.]
 [2264. 3432. 4388. ... 4005. 3063. 3697.]
 ...
 [2812. 3906. 4005. ... 5092. 3729. 4598.]
 [3006. 3083. 3063. ... 3729. 4316. 3850.]
 [2898. 3307. 3697. ... 4598. 3850. 4938.]]


In [ ]:
QUESTION 5

In [19]:
import pandas as pd
import numpy as np

def load_boston():
    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]
    return {'data': data, 'target': target}

boston = load_boston()
X = boston['data'][:, [0, 4, 5, 6]] 
y = boston['target'][:X.shape[0]]

x = np.linalg.lstsq(X, y, rcond=None)[0]

# Output weights
features = ['CRIM', 'NOX', 'RM', 'AGE']
for i in range(len(x)):
    relation = "direct" if x[i] > 0 else "inverse"
    print(f"The house price is in {relation} proportion to the {features[i]} ({x[i]:.4f})")


The house price is in inverse proportion to the CRIM (-0.1840)
The house price is in inverse proportion to the NOX (-19.3962)
The house price is in direct proportion to the RM (5.6736)
The house price is in inverse proportion to the AGE (-0.0228)


In [ ]:
QUESTION 6

In [31]:
import pandas as pd
import numpy as np

def load_boston():
    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]
    return {'data': data, 'target': target}

boston = load_boston()
X = boston['data'][:, [0, 4, 5, 6]]  # CRIM, NOX, RM, AGE
y = boston['target'][:X.shape[0]]

X = np.column_stack([np.ones(X.shape[0]), X])

w = np.linalg.inv(X.T @ X) @ X.T @ y

# Display weights
feature_names = ['Intercept', 'CRIM', 'NOX', 'RM', 'AGE']
for name, weight in zip(feature_names, w):
    relation = "direct" if weight > 0 else "inverse"
    print(f"{name}: {weight:.4f} ({relation} relationship)")

Intercept: -19.8550 (inverse relationship)
CRIM: -0.1931 (inverse relationship)
NOX: -7.8411 (inverse relationship)
RM: 7.8905 (direct relationship)
AGE: -0.0314 (inverse relationship)


In [ ]:
QUESTION 13

In [23]:
from sympy import symbols, diff, log, exp
x, k, a = symbols('x k a')

#A.
f = x**3 - 1
diff(f,x)

#B
f = log(x**2 - 3*k)
diff(f,x)

#C 
f = exp(a*x**5)
diff(f,x)

5*a*x**4*exp(a*x**5)

In [ ]:
QUESTION 14

In [27]:
x, y = symbols('x y')
f = exp(x**2 + 2*y**2)

#First Derivatiuve
print('..........1st Deriv......')
fx = diff(f,x)
print(fx)
fy = diff(f,y)
print(fy)

#second derivatiuve
print('..........2nd Deriv......')
fxx = diff(fx, x)
print(fxx)
fyy = diff(fy,y)
print(fyy)
fxy = diff(fx, y)
print(fxy)
fyx = diff(fy, x)
print(fyx)

..........1st Deriv......
2*x*exp(x**2 + 2*y**2)
4*y*exp(x**2 + 2*y**2)
..........2nd Deriv......
4*x**2*exp(x**2 + 2*y**2) + 2*exp(x**2 + 2*y**2)
16*y**2*exp(x**2 + 2*y**2) + 4*exp(x**2 + 2*y**2)
8*x*y*exp(x**2 + 2*y**2)
8*x*y*exp(x**2 + 2*y**2)
